#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""Freeze independent HKDF-SHA512 / SipHash-2-4 native-provider vectors."""
import argparse
import hashlib
import hmac
import json
from pathlib import Path

from generate_encrypted_casefold import Provider, known_answers

LENGTHS = list(range(64)) + [254, 255, 256, 257, 4080]


def generate(provider):
    rows = []
    for offset, nonce_start in ((3, 0), (3, 16), (4, 0)):
        master = bytes((index * 7 + offset) & 255 for index in range(64))
        nonce = bytes(range(nonce_start, nonce_start + 16))
        info = b'fscrypt\0\x05' + nonce
        extracted = hmac.new(bytes(64), master, hashlib.sha512).digest()
        key = hmac.new(extracted, info + b'\x01', hashlib.sha512).digest()[:16]
        message = bytes((index * 11 + 3) & 255 for index in range(max(LENGTHS)))
        answers = [int.from_bytes(provider.siphash(key, message[:length]), 'little')
                   for length in LENGTHS]
        rows.append(dict(master_offset=offset, nonce=nonce.hex(), key=key.hex(), answers=answers))
    return rows


def header(rows):
    text = ['/* SPDX-License-Identifier: BSD-3-Clause */',
            '/* Generated by generate_native_siphash.py using independent HMAC-SHA512',
            ' * and OpenSSL EVP SipHash (64-bit output, 2/4 rounds). Public test keys only. */',
            '#ifndef MACHLIN_EXT4_NATIVE_SIPHASH_VECTORS_H',
            '#define MACHLIN_EXT4_NATIVE_SIPHASH_VECTORS_H', '',
            '#include <stddef.h>', '#include <stdint.h>', '',
            '#define NATIVE_SIPHASH_INPUT_MAX 4080U',
            f'#define NATIVE_SIPHASH_LENGTHS {len(LENGTHS)}U',
            'struct native_siphash_vector {', '\tuint8_t master_offset;',
            '\tuint8_t nonce[16];', '\tuint8_t key[16];',
            '\tuint64_t answers[NATIVE_SIPHASH_LENGTHS];', '};', '',
            'static const size_t native_siphash_lengths[NATIVE_SIPHASH_LENGTHS] = {']
    for start in range(0, len(LENGTHS), 12):
        text.append('\t' + ', '.join(str(value) for value in LENGTHS[start:start + 12]) + ',')
    text.extend(['};', '', 'static const struct native_siphash_vector native_siphash_vectors[] = {'])
    for row in rows:
        text.extend(['\t{', f'\t\t{row["master_offset"]},'])
        for field in ('nonce', 'key'):
            value = bytes.fromhex(row[field])
            text.append('\t\t{')
            for start in range(0, len(value), 8):
                text.append('\t\t\t' + ', '.join(f'0x{byte:02x}' for byte in value[start:start + 8]) + ',')
            text.append('\t\t},')
        text.append('\t\t{')
        for start in range(0, len(LENGTHS), 2):
            text.append('\t\t\t' + ', '.join(f'UINT64_C(0x{value:016x})'
                         for value in row['answers'][start:start + 2]) + ',')
        text.extend(['\t\t},', '\t},'])
    text.extend(['};', '', '#endif', ''])
    return '\n'.join(text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    provider = Provider()
    known_answers(provider)
    rows = generate(provider)
    args.output.mkdir(parents=True, exist_ok=False)
    (args.output / 'native_siphash_vectors.h').write_text(header(rows))
    (args.output / 'vectors.json').write_text(json.dumps({
        'provider': provider.version, 'library': provider.library, 'lengths': LENGTHS,
        'input': '(index * 11 + 3) modulo 256', 'profiles': rows,
        'sources': ['https://www.rfc-editor.org/rfc/rfc5869',
                    'https://docs.openssl.org/3.0/man7/EVP_MAC-Siphash/',
                    'https://docs.kernel.org/filesystems/fscrypt.html#dirhash-keys',
                    'https://github.com/veorq/SipHash']}, indent=2) + '\n')
    print(f'PASS generated {len(rows)} profiles, {len(LENGTHS)} lengths, {len(rows) * len(LENGTHS)} hashes')


if __name__ == '__main__':
    main()
